//WT-List-2
=MAP(
 UNIQUE(
  FILTER(
   IRIS_List_All!C2:C&"♦"&IRIS_List_All!E2:E,
   IRIS_List_All!C2:C<>"",
   COUNTIFS(
    'WT-List-1'!B:B,IRIS_List_All!C2:C,
    'WT-List-1'!D:D,IRIS_List_All!E2:E
   )=0
  )
 ),
 LAMBDA(x,
 {
  INDEX(SPLIT(x,"♦"),1),
  TEXTJOIN(", ",TRUE,
   FILTER(
    IRIS_List_All!B2:B,
    (IRIS_List_All!C2:C=INDEX(SPLIT(x,"♦"),1))*
    (IRIS_List_All!E2:E=INDEX(SPLIT(x,"♦"),2))
   )
  ),
  INDEX(SPLIT(x,"♦"),2)
 }
 )
)
